version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  # create_infrastructure: 
  #     docker:
  #       - image: amazon/aws-cli
  #     steps:
  #       - checkout
  #       - run:
  #           name: Create Cloudformation Stack
  #           command: |
  #             aws cloudformation deploy \
  #               --template-file template.yml \
  #               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #               --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            #- "b8:86:64:75:83:97:06:da:35:38:ae:12:34:6d:91:78"
            - "9c:a4:01:43:cc:7f:2c:1c:b6:e8:6f:82:c1:d5:17:d3"
      - run:
          name: Install Ansible
          command: |
            pip install --user ansible \
            pip install --upgrade --user ansible \
            ansible --version
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml 

workflows:
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure