- name: update apt packages
  become: yes
  apt:
    update_cache: yes

# - name: upgrade apt packages
#   become: yes
#   apt:
#     upgrade: yes


# - name: correct apt packages
#   become: yes
#   shell: |
#     sudo dpkg --configure -a

# - name: remove dependencies that are no longer required
#   become: yes
#   apt:
#     autoremove: yes

- name: install node
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create dir
  file:
    path: ~/web
    state: directory

- name: copy index.js
  become: yes
  copy:
    src: index.js
    dest: ~/web/index.js

- name: start node
  shell: |
    pm2 start ~/web/index.js -f
    
